### ISSUE TITLE
Power strip in office needs securing

### ISSUE THREAD

**Issue by andrewhamon** [andrewhamon/square-one#1]
Its hard to unplug things from the power strip in the office without dragging the whole power strip around or having to use two hands. Some zip ties could go along way.

**Comment by andrewhamon** [comment]
Done

![img_3303 2](https://cloud.githubusercontent.com/assets/5134584/6090623/9bcbb646-ae4d-11e4-9832-79044b6aae09.JPG)

**Comment by stevenpetryk** [comment]
Reopening this until you close the tabs on your Macbook charger.

**Comment by andrewhamon** [comment]
Fins open to aid in heat dissipation. Closing.
