### ISSUE TITLE
Living room still has no couch

### ISSUE THREAD

**Issue by andrewhamon** [andrewhamon/square-one#6]
If users try to sit in the living room they will most likely get a method missing or uninitialized constant error

**Comment by stevenpetryk** [comment]
We may be able to resolve this by adding this:

```ruby
require 'ikea-ruby'

couch = IKEA::Catalog.find("S19875765", "Nordvalla gray")
living_room.add_furniture(couch)
```

[Nordvalla gray seems to be a good color](http://www.ikea.com/us/en/catalog/products/S19875765/#/S19046258).

**Comment by andrewhamon** [comment]
But [Tygelsjö beige](http://www.ikea.com/us/en/catalog/products/S19875765/#/S99932597) is $100 cheaper

**Comment by stevenpetryk** [comment]
This may be resolved in a few days. I'll be bringing a couch from Tampa. Stay tuned.
